// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/borzoj/go-lambda-test/pkg/http"
	weather2 "github.com/borzoj/go-lambda-test/pkg/weather"
)

// Injectors from wire.go:

func CreateWeatherService() (weather2.Service, error) {
	client, err := http.NewClient()
	if err != nil {
		return weather2.Service{}, err
	}
	service, err := weather2.NewService(client)
	if err != nil {
		return weather2.Service{}, err
	}
	return service, nil
}
